# Pre-commit hooks for code quality
# See https://pre-commit.com for more information
repos:
  # General file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key

  # Python code formatting - Black
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=100']

  # Python imports sorting - isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '100']

  # Python linting - Ruff (fast Python linter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  # Python type checking - MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-redis
          - types-python-dateutil
        args: 
          - --ignore-missing-imports
          - --no-strict-optional
          - --warn-unused-ignores
        exclude: ^(tests/|test_|conftest\.py|setup\.py)

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
      - id: bandit
        args: ['-ll', '--skip', 'B101,B303,B601,B602,B607']
        exclude: ^(tests/|test_)

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ['--disable', 'MD013', '--disable', 'MD033', '--disable', 'MD041']

  # Secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]

  # Architecture validation (custom hooks)
  - repo: local
    hooks:
      - id: check-core-imports
        name: Check core layer imports
        entry: python scripts/check_architecture.py
        language: python
        files: ^apps/api/src/core/
        pass_filenames: true

      - id: prohibit-pandas-in-core
        name: Prohibit pandas in core
        entry: bash -c 'if grep -r "import pandas\|from pandas" apps/api/src/core/ --include="*.py" 2>/dev/null | grep -v "^#"; then echo "ERROR: pandas found in core layer!"; exit 1; fi'
        language: system
        files: ^apps/api/src/core/.*\.py$
        pass_filenames: false

      - id: prohibit-sqlalchemy-in-core
        name: Prohibit SQLAlchemy in core
        entry: bash -c 'if grep -r "import sqlalchemy\|from sqlalchemy" apps/api/src/core/ --include="*.py" 2>/dev/null | grep -v "^#"; then echo "ERROR: SQLAlchemy found in core layer!"; exit 1; fi'
        language: system
        files: ^apps/api/src/core/.*\.py$
        pass_filenames: false

      - id: prohibit-fastapi-in-core
        name: Prohibit FastAPI in core
        entry: bash -c 'if grep -r "import fastapi\|from fastapi" apps/api/src/core/ --include="*.py" 2>/dev/null | grep -v "^#"; then echo "ERROR: FastAPI found in core layer!"; exit 1; fi'
        language: system
        files: ^apps/api/src/core/.*\.py$
        pass_filenames: false

      - id: prohibit-sys-path-manipulation
        name: Prohibit sys.path manipulation
        entry: bash -c 'if grep -r "sys\.path\.\(append\|insert\|extend\)" apps/api/src/ --include="*.py" 2>/dev/null | grep -v "^#"; then echo "ERROR: sys.path manipulation found!"; exit 1; fi'
        language: system
        files: ^apps/api/src/.*\.py$
        pass_filenames: false

# Configuration for specific tools
default_language_version:
  python: python3.11

# Files to exclude globally
exclude: |
  (?x)^(
    .*\.min\.js|
    .*\.min\.css|
    .*/migrations/.*|
    .*/static/.*|
    .*/vendor/.*|
    build/.*|
    dist/.*|
    node_modules/.*|
    venv/.*|
    .*\.egg-info/.*|
    __pycache__/.*|
    \.git/.*|
    \.mypy_cache/.*|
    \.pytest_cache/.*|
    \.ruff_cache/.*|
    \.coverage.*|
    htmlcov/.*
  )$